# .github/workflows/run-makefile-for-isabelle-docker-image.yml
# Author: Daniel M. Zimmerman
# Created: 2026-03-04
# Modified: 2026-03-09

name: Run Makefile for Isabelle Docker Image

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'docker/isabelle-e2eviv/**'
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  test:
    strategy:
      # Because we want to build as efficiently as possible in
      # GitHub Actions, we build each platform's image on its own
      # native builder; as we are not deploying them automatically,
      # this demonstrates that both can build while using minimal
      # resources.
      fail-fast: false
      matrix:
        include:
        - platform: linux/amd64
          runner: ubuntu-latest
        - platform: linux/arm64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Save Space on Runner Image
        run: |
          echo "Space Before Cleaning"
          df -h

          # Remove Java (JDKs)
          sudo rm -rf /usr/lib/jvm

          # Remove .NET SDKs
          sudo rm -rf /usr/share/dotnet

          # Remove Swift toolchain
          sudo rm -rf /usr/share/swift

          # Remove Haskell (GHC)
          sudo rm -rf /usr/local/.ghcup

          # Remove Julia
          sudo rm -rf /usr/local/julia*

          # Remove Android SDKs
          sudo rm -rf /usr/local/lib/android

          # Remove Chromium
          sudo rm -rf /usr/local/share/chromium

          # Remove Microsoft/Edge and Google Chrome builds
          sudo rm -rf /opt/microsoft /opt/google

          # Remove Azure CLI
          sudo rm -rf /opt/az

          # Remove PowerShell
          sudo rm -rf /usr/local/share/powershell

          # Remove CodeQL and other toolcaches
          sudo rm -rf /opt/hostedtoolcache

          echo "Space After Cleaning"
          df -h

      - name: Uninstall Old Docker
        run: |
          sudo apt-get remove -y docker.io docker-doc docker-compose docker-compose-v2 podman-docker containerd runc

      - name: Install Current Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Run `make image` in `docker/isabelle-e2eviv`
        run: |
          echo "Processing docker image"
          cd docker/isabelle-e2eviv
          IMAGE_PLATFORM=${{ matrix.platform }} make image
