# File: .github/workflows/test-validity-of-isabelle-files.yml
# Author: Frank Zeyda
# Created: 2026-03-02
# Modified: 2026-03-31

name: Test Validity of Isabelle Files

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'models/cryptography/isabelle/**'
  push:
    branches:
      - 'main'
    paths:
      - 'models/cryptography/isabelle/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Isabelle/HOL CA Session
    runs-on: ubuntu-latest

    container:
      image: freeandfair/isabelle-e2eviv:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Show Isabelle version
        run: isabelle version

      - name: Build CA session
        run: |
          # Workaround: GitHub containers set HOME to /github/home
          # (There seems to be no clean way to adjust HOME.)
          export HOME="/home/isabelle"
          cd models/cryptography/isabelle
          isabelle build -v -D E2EVIV
