# .github/workflows/test-validity-of-assurance-case-skeleton.yml
# Author: Daniel M. Zimmerman
# Created: 2025-05-15
# Modified: 2026-03-31

# This workflow tests the validity of the assurance case skeleton
# by building it (and the threat model database).

name: Test Validity of Assurance Case Skeleton

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths:
      - 'assurance/**'
      - 'models/threat-model/**'

  workflow_dispatch:

jobs:
  threat-model:
    name: Run "Make" on Assurance Case Skeleton
    runs-on: ubuntu-latest
    steps:
      - name: Install Packages
        run: sudo apt-get install build-essential

      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set Up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Bootstrap Assurance Python Environment
        run: |
          cd assurance
          make python-venv

      - name: Run `make ci` in Assurance Directory
        run: |
          cd assurance
          make ci

      - name: Save the Generated Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: assurance_case_skeleton
          path: assurance/advocate-project
